[build]
  functions = "functions/"
  publish = "dist/"
  command = "./build.sh"

[dev]
  command = "npm start"
  targetPort = 1234
  autoLaunch = true
  framework = "#custom"

[functions]
  node_bundler = "esbuild"
