[build]
  functions = "functions/"
  publish = "dist/"
  command = "./build.sh"

[dev]
  command = "npm start"
  targetPort = 1234
  autoLaunch = true
  framework = "#custom"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/glib/js/script.js"
  to = "https://plausible.io/js/script.js"
  status = 200
  force = true

[[redirects]]
  from = "/glib/api/event"
  to = "https://plausible.io/api/event"
  status = 200
  force = true
