[build]
  publish = "dist/"
  command = "npm install -g elm && npm install && npx --no-install elm-tooling install && npx elm-tailwind-modules --dir ./tw --tailwind-config tailwind.config.js && mkdir .elm-pages && npx elm-pages build"

[dev]
  command = "npm start"
  targetPort = 1234
  autoLaunch = true
  framework = "#custom"
