[build]
  publish = "dist/"
  command = "npm run build"

[[redirects]]
  from = "/ingest/static/*"
  to = "https://us-assets.i.posthog.com/static/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/ingest/*"
  to = "https://us.i.posthog.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/stats/*"
  to = "https://umami.natebraun.com/:splat"
  status = 200
  force = true
